title: The Unconventional DBA
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    #- text: Gallery
      #url: /gallery
    #- text: Shop
      #url : /shop
    - text: Contact Me
      url : /contact
    #- text: Styleguide
      #url: /styleguide
    #- text: Get Started
      #url: /get-started

# Edit these details

author_logo: profile.png
author: Tom
author_bio: Hello, I'm Tom and I've been a SQL server database administrator/ developer for just over two years. I was unsure about starting this blog at first as the SQL community has such great content and some immensely knowledgeable people. However if you are like me I always like to know how people arrived at the answer and not just what the answer is. Hopefully this blog will do just that and will not only help people find the answers they are looking for but also how I got there. If you are reading this thank you for taking the time to visit my site!
author_email: "theunconventionaldba@icloud.com"
author_location: Uk
author_website_url: 
typewrite-text: Welcome to my blog

author_work_experiences:
            - company_name: Emis
              company_logo: Emis.png
              company_url: https://www.emishealth.com/
              designation: Database Developer
              description: 
              visibility: true
            - company_name: The Data Shed
              company_logo: DataShed.png
              company_url: https://www.thedatashed.co.uk/
              designation: Database Administrator
              description: 
              visibility: true


#author_education_details:
              #- college_logo: mit.png
                #college_url: https://mit.org
                #college_name: MIT
                #college_degree: CS Engineer
                #description: Bachelor of Technology
                #visibility: true

author_project_details:
              - project_thumbnail: Proc.png
                project_title: Alert stored proc
                project_description: A store procedure to enable operator alerts and assign these to agent jobs or operators.
                project_url: https://github.com/Tom-Fynes/SP_CreateAndEnableFailureAlerts
                visibility: true

# social links
#twitter_username: johndoe
github_username:  Tom-Fynes
linkedin_username: thomas-f-b00607163/
#behance_username: johndoe
#instagram_username: johndoe
##telegram_username: johndoe
#medium_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: TomFynes

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: theunconventionaldba@icloud.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
#collections:
  #- products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
